In [1]:
import numpy as np 


all these operation is able to perform because this size of array or dimention is same


In [2]:
x=np.random.randint(10,120,(4,4))
y=np.random.randint(10,120,(4,4))


In [3]:
print(x)
print(y)

[[ 49  61  97  15]
 [ 59  31  36  90]
 [ 58  68 107  54]
 [ 11 116 109  97]]
[[ 86  81  38  33]
 [ 98  82  68  47]
 [ 67  46  72 116]
 [ 89  69  30 104]]


In [4]:
x+y

array([[135, 142, 135,  48],
       [157, 113, 104, 137],
       [125, 114, 179, 170],
       [100, 185, 139, 201]])

In [5]:
x-y

array([[-37, -20,  59, -18],
       [-39, -51, -32,  43],
       [ -9,  22,  35, -62],
       [-78,  47,  79,  -7]])

In [6]:

x*y

array([[ 4214,  4941,  3686,   495],
       [ 5782,  2542,  2448,  4230],
       [ 3886,  3128,  7704,  6264],
       [  979,  8004,  3270, 10088]])

what if we change the dimention 

In [7]:
a=np.random.randint(4,40,(4,5))
b=np.random.randint(4,40,(4))

In [9]:
a


array([[21, 20, 33, 22, 16],
       [26, 14, 23, 17, 14],
       [20, 29, 27, 29, 12],
       [14, 21, 37, 33, 36]])

In [10]:
b


array([39,  8, 23, 39])

In [11]:
#these opeation is not able to perform because dimention is not same
a+b

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [12]:
#but if i change x
x=np.random.randint(10,120,(4))


In [14]:
#this is noe performable because of the concept of broadcasting
x+y

array([[178, 138, 140,  59],
       [190, 139, 170,  73],
       [159, 103, 174, 142],
       [181, 126, 132, 130]])

In [15]:
u=np.random.randint(20,30,(4,3))
v=np.random.randint(20,30,(1,4))


In [19]:
v=np.random.randint(20,30,(4,1))
u+v

array([[46, 47, 54],
       [57, 51, 56],
       [44, 49, 43],
       [53, 49, 54]])

In [16]:
u
v

array([[26, 25, 23, 23]])

In [17]:
u+v

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [22]:
x=np.array([[1],[2],[3]])

x.shape

(3, 1)

In [26]:
y=np.random.randint(20,30,(3,3))
x+y


array([[27, 27, 27],
       [28, 22, 26],
       [25, 24, 25]])

In [27]:
x

array([[1],
       [2],
       [3]])