In [13]:
import numpy as np
l=[for i in range(100)]

print(l)


SyntaxError: invalid syntax (908884377.py, line 2)

In [ ]:
import numpy as np
n=np.zeros(3)
print(n)

[0. 0. 0.]


In [ ]:
l=[10,20,30,50,60]
_num=np.array(l)
print(_num)
print(_num[1])

[10 20 30 50 60]
20


In [ ]:
print(_num.data)
print(_num.shape)
print(_num.dtype)
print(_num.strides)

(5,)
int32
(4,)


In [ ]:
l=[[1,2,3,4,2,5],[2,4,5,6,7,7],[3,5,7,8,9,9],[7,6,4,3,6,6]]
num_arr1=np.array(l,dtype=int)
print(num_arr1)


[[1 2 3 4 2 5]
 [2 4 5 6 7 7]
 [3 5 7 8 9 9]
 [7 6 4 3 6 6]]


In [ ]:
print(num_arr1.data)
print(num_arr1.shape)
print(num_arr1.strides)
print(num_arr1.dtype)

(4, 6)
(24, 4)
int32


In [ ]:
print(num_arr1[0,0])

print(num_arr1[1][2:5])

1
[5 6 7]


In [ ]:
num_arr1[2:4,1:4]

array([[5, 7, 8],
       [6, 4, 3]])

In [ ]:
l1=[10,20,30,40,50]
x=np.random.randint(1,30,6) # 1 columns assure that you will get random value from 1-30 and you will get 6 random values

x

array([ 1,  1,  8,  8, 21,  9])

In [ ]:
l3=[2*i for i in l1]
l3

[20, 40, 60, 80, 100]

In [ ]:
z=l1+l3
z

[10, 20, 30, 40, 50, 20, 40, 60, 80, 100]

In [14]:
import numpy as np
x=np.array([1,3,4,5,6,87],dtype=int)
y=np.array([33,44,55,77,8,77],dtype=int)


z=x**y

# z=x+y

In [17]:
import numpy as np
x=np.random.randint(1,50,(4,5))
x

array([[49, 30, 48, 39,  9],
       [28,  5, 43,  6, 44],
       [45, 42, 39, 43, 35],
       [ 1, 22, 16, 48,  5]])

In [20]:
boolean_arr


NameError: name 'boolean_arr' is not defined