In [12]:
import numpy as np
l=[for i in range(100)]

print(l)


SyntaxError: invalid syntax (908884377.py, line 2)

In [ ]:
import numpy as np
n=np.zeros(3)
print(n)

[0. 0. 0.]


In [ ]:
l=[10,20,30,50,60]
_num=np.array(l)
print(_num)
print(_num[1])

[10 20 30 50 60]
20


In [13]:
print(_num.data)
print(_num.shape)
print(_num.dtype)
print(_num.strides)

(5,)
int32
(4,)


In [15]:
l=[[1,2,3,4,2,5],[2,4,5,6,7,7],[3,5,7,8,9,9],[7,6,4,3,6,6]]
num_arr1=np.array(l,dtype=int)
print(num_arr1)


[[1 2 3 4 2 5]
 [2 4 5 6 7 7]
 [3 5 7 8 9 9]
 [7 6 4 3 6 6]]


In [16]:
print(num_arr1.data)
print(num_arr1.shape)
print(num_arr1.strides)
print(num_arr1.dtype)

(4, 6)
(24, 4)
int32


In [20]:
print(num_arr1[0,0])

print(num_arr1[1][2:5])

1
[5 6 7]
